services:
  mysql:
    image: mysql:8.0
    container_name: salemaster-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salemaster
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
